### PR TITLE
Tic Tac Toe | User interface

### PR DESCRIPTION
**Pull request by uzairali19**
# Tic Tac Toe Setup | Milestone 2

Tic-tac-toe, noughts, and crosses is a paper-and-pencil game for two players, X and O, who take turns marking the spaces in a 3×3 grid. The player who succeeds in placing three of their marks in a diagonal, horizontal, or vertical row is the winner. It is a solved game with a forced draw assuming the best play from both players.

## Strategy

A player can play a perfect tic-tac-toe game (to win or at least draw) if, each time it is their turn to play, they choose the first available move from the following list, as used in Newell Simon's 1972 tic-tac-toe program.[16]

- Win: If the player has two in a row, they can place a third to get three in a row.
- Block: If the opponent has two in a row, the player must play the third themselves to block the opponent.
- Fork: Create an opportunity where the player has two ways to win (two non-blocked lines of 2).
- Blocking an opponent's fork: If there is only one possible fork for the opponent, the player should block it. Otherwise, the player should block all forks in any way that simultaneously allows them to create two in a row. Otherwise, the player should create a two in a row to force the opponent into defending, as long as it doesn't result in them creating a fork. For example, if "X" has two opposite corners and "O" has the center, "O" must not play a corner move to win. (Playing a corner move in this scenario creates a fork for "X" to win.)
- Center: A player marks the center. (If it is the first move of the game, playing a corner move gives the second player more opportunities to make a mistake and may therefore be the better choice; however, it makes no difference between perfect players.)
- Opposite corner: If the opponent is in the corner, the player plays the opposite corner.
- Empty corner: The player plays in a corner square.
- Empty side: The player plays in a middle square on any of the 4 sides.

## Authors

👤 **Uzair**

- LinkedIn: [LinkedIn](https://www.linkedin.com/in/uzair-ali-964187166/)
- GitHub: [@githubhandle](https://github.com/uzairali19)

### CODE REVIEW

**Review by emmanuellekamwa — CHANGES_REQUESTED** [review]
**STATUS: CHANGES REQUESTED 🛑🛠**
Hi @uzairali19 👋🏽
You did a good job so far but there are things that must be addressed to have this milestone approved 👀👇🏽:

- [x] All of your code is supposed to be inside the main.rb file since it is responsible for user interaction.
- [x] Game tells which player turn it is. Check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/player_turn.png).
- [x] Game asks the player to select from available moves. Check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/select_play.png).
- [x] Game informs the player if the selected move is invalid (without computing what an invalid move is). Check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/invalid_move.png).
- [x] Game displays board after the player move (without computing which spots on the board are taken). Check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/player_turn.png).
- [x] Game informs player if the selected move is a winning move (without computing the winning move). Check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_win%2059.png).
- [x] Game informs player if the selected move is a draw move (without computing draw). Check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png).
- [x] Game repeats all actions for the next player's move. Check this [gif](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif).
- [x] You have to add a loop inside your code and the while loop is highly recommended. Check this code for an overview 👇🏽 `
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
````
  Just apply those changes and when you are done request another code review. Good luck and happy coding 👨🏽‍💻👨🏽‍💻💪🏽💪🏽.

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
-------------------
Hello @uzairali19, great job you are doing in this milestone :clap: :+1: 
However, there are a few changes to make to complete this milestone :hammer_and_wrench: see them below :eyes: :point_down: 
----------------

- [x] Please validate the user's input so it cannot be empty. 

Screenshot from 2021-06-23 10-21-35

- [x] I only can be able to make 3 moves and the game finish. Please check that 
- [x] The user can input whatever and the game continues. 

Screenshot from 2021-06-23 10-27-42

-----------------
Please fix these required changes and send ti again for another review :1st_place_medal: :smile: 
HAPPY CODING!!!

**Review by BrianSammit — APPROVED** [review]
STATUS APPROVED :green_circle: :clap: 
------------
Hello again, great job working on the required changes :+1: :100: 
------------
Now you can merge this branch and move tho the next milestone :100: :1st_place_medal: 
HAPPY CODING!!!!

**Comment by uzairali19** [comment]
> ## STATUS APPROVED 🟢 👏
> ## Hello again, great job working on the required changes 👍 💯
> Now you can merge this branch and move tho the next milestone 💯 🥇
> HAPPY CODING!!!!
> 
> 

Hello Brain,

Thank you so much. Appreciate it. 👍🏻

Regards,
Uzair

**Pull request merged**
